### ISSUE TITLE
Fatal bugs in the Activity page

### ISSUE THREAD

**Issue by IJDesign** [Stasonis/fitbit-api-example-android#11]
Hi friends, did anyone know what's the fatal bug in the UserDataActivity? Whenever I open the ACTIVITY page, the app was forced to stop. The log of the error is as follows. Could you give me some hints to debug it? Thanks.

`02-28 09:31:00.719 701-915/? V/AudioPolicyEffects: releaseOutputSessionEffects: no output processing was attached to this stream
02-28 09:31:00.760 15414-15414/com.fitbit.sampleandroidoauth2 D/AndroidRuntime: Shutting down VM
02-28 09:31:00.761 15414-15414/com.fitbit.sampleandroidoauth2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.fitbit.sampleandroidoauth2, PID: 15414
                                                                                java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                                    at com.fitbit.sampleandroidoauth2.fragments.WeightLogFragment.bindWeightLogs(WeightLogFragment.java:78)
                                                                                    at com.fitbit.sampleandroidoauth2.fragments.WeightLogFragment.onLoadFinished(WeightLogFragment.java:59)
                                                                                    at com.fitbit.sampleandroidoauth2.fragments.WeightLogFragment.onLoadFinished(WeightLogFragment.java:27)
                                                                                    at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:489)
                                                                                    at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:457)
                                                                                    at android.content.Loader.deliverResult(Loader.java:144)
                                                                                    at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
                                                                                    at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
                                                                                    at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                                    at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-28 09:31:00.763 1555-4043/? W/ActivityManager:   Force finishing activity com.fitbit.sampleandroidoauth2/.UserDataActivity
02-28 09:31:00.766 1555-4043/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger `

**Comment by IJDesign** [comment]
I found the bug was in the "WeightLogFragment.java." By temporarily disabling the "weight" fragment in the UserDataPagerAdapter.java, I could use and try the other functions.
